create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table producto (codigo integer not null, descripcion varchar(255), imagen tinyblob, nombre varchar(255), precio float not null, primary key (codigo)) engine=InnoDB;
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table producto (codigo integer not null, descripcion varchar(255), imagen tinyblob, nombre varchar(255), precio float not null, primary key (codigo)) engine=InnoDB;
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table producto (codigo integer not null, descripcion varchar(255), imagen tinyblob, nombre varchar(255), precio float not null, primary key (codigo)) engine=InnoDB;
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table producto (codigo integer not null, descripcion varchar(255), imagen tinyblob, nombre varchar(255), precio float not null, primary key (codigo)) engine=InnoDB;
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table producto (codigo integer not null, descripcion varchar(255), imagen tinyblob, nombre varchar(255), precio float not null, primary key (codigo)) engine=InnoDB;
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
create table cliente (codigo integer not null, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), telefono varchar(255), vip bit not null, primary key (codigo)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table producto (codigo integer not null, descripcion varchar(255), imagen tinyblob, nombre varchar(255), precio float not null, primary key (codigo)) engine=InnoDB;
create table proveedor (codigo integer not null, apellidos varchar(255), nombre varchar(255), primary key (codigo)) engine=InnoDB;
